#!/bin/sh -e

# include configuration file that should do all checks and setup variables
. ./configure.sh

## start VS CODE	
echo '################################################################################################'
echo '############################### STARTED VS CODE SERVE ##########################################' 
exec chpst -u $USER_NAME $VSCODE_BIN \
        --host 0.0.0.0 --port $VSCODE_PORT \
        --connection-token $VSCODE_TOKEN \
        --telemetry-level off --accept-server-license-terms \
        --server-data-dir=$VSCODE_SERVER_DATA_DIR \
        --user-data-dir=$VSCODE_SERVER_DATA_DIR/data/ \
        --extensions-dir=$VSCODE_SERVER_DATA_DIR/extensions &

# save PID of server and wait to finish
mkdir -p ./supervise
echo $! > ./supervise/pid_vscode_serve
wait $!        