#!/bin/bash -e

USER_NAME=${USER_NAME:-user}
USER_HOME=${BASE%"/"}/$USER_NAME

JUPYTER_PORT=${JUPYTER_PORT:-8080}

export HOME=$USER_HOME
chpst -u $USER_NAME bash /etc/service/jupyter/config.sh 2>&1

add_auth_token_motd() {
	AUTH_TOKEN=$1
	
	# first remove any existing tokens 
	line=$(grep -n 'TOKEN (jupyter)' /etc/motd | cut -f1 -d:)
	if [ ! -z "$line" ]; then
		sed -i "$((line))d" /etc/motd
	fi 
	
	# save value that will be appended to MOTD into temp file
	cat > /tmp/motd.jupyter <<- EOF
	TOKEN (jupyter): ${AUTH_TOKEN}
	EOF
	
	# append right before CONTAINER STATUS
	line=$(grep -n "CONTAINER STATUS:" /etc/motd | cut -f1 -d:)
	sed -i "$((line-1))r/tmp/motd.jupyter" /etc/motd
	
	# remove temp file
	rm /tmp/motd.jupyter
}

TOKEN=`date +%s | sha256sum | base64 | head -c 32`
echo $TOKEN | chpst -u $USER_NAME tee $USER_HOME/jupyter.token

add_auth_token_motd $TOKEN

exec chpst -u $USER_NAME jupyter notebook --NotebookApp.token=$TOKEN --no-browser --ip="0.0.0.0" --port="$JUPYTER_PORT" --notebook-dir=${USER_HOME}/workspace 2>&1

