#!/bin/sh
set -eu

truthy() {
    case "${1:-}" in
        1|true|TRUE|yes|YES|on|ON) return 0 ;;
        0|false|FALSE|no|NO|off|OFF|"") return 1 ;;
        *) return 1 ;;
    esac
}

# Non-default by design: CCC images only install/activate the external
# ccc-agent-containment runtime when explicitly requested at container startup.
if ! truthy "${CCC_AGENT_CONTAINMENT_ENABLE:-0}"; then
    exit 0
fi

repo="${CCC_AGENT_CONTAINMENT_REPO:-https://github.com/vicoslab/ccc-agent-containment.git}"
ref="${CCC_AGENT_CONTAINMENT_REF:-main}"
install_dir="${CCC_AGENT_CONTAINMENT_INSTALL_DIR:-/opt/ccc-agent}"
config_dir="${CCC_AGENT_CONTAINMENT_CONFIG_DIR:-/etc/ccc-agent}"
config_file="${CCC_AGENT_CONFIG:-${config_dir}/config.json}"
link_dir="${CCC_AGENT_CONTAINMENT_LINK_DIR:-/usr/local/bin}"
enable_shims="${CCC_AGENT_CONTAINMENT_ENABLE_SHIMS:-0}"
shim_agents="${CCC_AGENT_CONTAINMENT_SHIM_AGENTS:-codex claude hermes opencode}"
branchfs_bin="${CCC_AGENT_CONTAINMENT_BRANCHFS_BIN:-}"

if ! command -v git >/dev/null 2>&1; then
    echo "ccc-agent-containment: git is required to install ${repo}" >&2
    exit 1
fi

umask 022
tmpdir="$(mktemp -d)"
cleanup() {
    rm -rf "${tmpdir}"
}
trap cleanup EXIT INT TERM

src="${tmpdir}/src"
echo "ccc-agent-containment: installing ${repo}@${ref} into ${install_dir}"
if ! git clone --depth 1 --branch "${ref}" "${repo}" "${src}"; then
    echo "ccc-agent-containment: shallow clone failed; retrying full clone" >&2
    git clone "${repo}" "${src}"
    git -C "${src}" checkout "${ref}"
fi

rm -rf "${tmpdir}/runtime"
mkdir -p "${tmpdir}/runtime"
for path in bin ccc_agent config hooks scripts shims README.md docs; do
    if [ -e "${src}/${path}" ]; then
        cp -a "${src}/${path}" "${tmpdir}/runtime/${path}"
    fi
done

rm -rf "${install_dir}"
mkdir -p "$(dirname "${install_dir}")"
cp -a "${tmpdir}/runtime" "${install_dir}"

# If BranchFS is already installed in the image/container, make the default
# ccc-agent config path work without baking BranchFS into the CCC image.
if [ -n "${branchfs_bin}" ] && [ -x "${branchfs_bin}" ]; then
    ln -sfn "${branchfs_bin}" "${install_dir}/bin/branchfs"
elif command -v branchfs >/dev/null 2>&1; then
    ln -sfn "$(command -v branchfs)" "${install_dir}/bin/branchfs"
else
    echo "ccc-agent-containment: warning: branchfs binary not found; set CCC_AGENT_CONTAINMENT_BRANCHFS_BIN before using branchfs backend" >&2
fi

mkdir -p "${link_dir}"
for bin in ccc-agent-run ccc-agent-launch ccc-agentctl; do
    if [ -x "${install_dir}/bin/${bin}" ]; then
        ln -sfn "${install_dir}/bin/${bin}" "${link_dir}/${bin}"
    fi
done

mkdir -p "${config_dir}"
if [ ! -f "${config_file}" ]; then
    user_name="${USER_NAME:-user}"
    home_subdir="${CCC_AGENT_HOME_SUBDIR:-}"
    state_dir="${CCC_AGENT_STATE_DIR:-/storage/user/.ccc-agent}"
    storage_user_base="${CCC_AGENT_STORAGE_USER_BASE:-/__real/storage_user}"
    storage_user_store="${CCC_AGENT_STORAGE_USER_STORE:-/__branchfs_store/storage_user}"
    cat > "${config_file}" <<EOF
{
  "_comment": "Generated by CCC runit startup when CCC_AGENT_CONTAINMENT_ENABLE=1. Keep root-owned and not writable by agents.",
  "state_dir": "${state_dir}",
  "backend": "branchfs",
  "branchfs_bin": "${install_dir}/bin/branchfs",
  "user": "${user_name}",
  "home_subdir": "${home_subdir}",
  "roots": [
    {
      "name": "storage_user",
      "base": "${storage_user_base}",
      "store": "${storage_user_store}",
      "visible": "/storage/user",
      "home_subdir": "${home_subdir}",
      "hide_paths": [".ssh", ".gnupg", ".netrc", ".aws", ".kube", ".docker/config.json", ".ccc-agent"]
    }
  ],
  "hide_patterns": [".env", ".env.*", "*.pem", "id_rsa*", "id_ed25519*", "credentials.json"]
}
EOF
    chmod 0644 "${config_file}"
fi

if truthy "${enable_shims}"; then
    for agent in ${shim_agents}; do
        ln -sfn "${install_dir}/shims/ccc-agent-shim.sh" "${link_dir}/${agent}"
    done
fi

echo "ccc-agent-containment: installed runtime; set CCC_AGENT_CONFIG=${config_file} for explicit use"
