#!/bin/sh

#############################################################################################
# functions

sv_stop() {
    echo "*** Stopping services"
    for s in $(ls -d /etc/service/*)
    do
        /sbin/sv stop $s
    done
}

# Include script for storing env vars and recovery mode with functions:
#   - init_environment_vars 
#   - init_recovery_mode
#   - finish_recovery_mode
. /etc/env_recovery_scripts.sh


#############################################################################################
# main

trap "sv_stop; exit" SIGTERM

# Store environment vars into /etc/envvars
init_environment_vars

# Initilaize recovery mode
init_recovery_mode
recovery_boot=$?

# Start pre-service scripts
echo "Starting pre-service scripts in /etc/runit_init.d"
for script in /etc/runit_init.d/*
do
    if [ -x "$script" ]; then
        echo >&2 "*** Running: $script"
        $script
        retval=$?
        if [ $retval != 0 ];
        then
            echo >&2 "*** Failed with return value: $retval"
            exit $retval
        fi
    fi
done

# Finalize recovery mode  if enabled
[ "$recovery_boot" -eq 0 ] && finish_recovery_mode

/usr/bin/runsvdir /etc/service &
wait
