#! /usr/bin/env bash

USER_NAME=${USER_NAME:-user}
USER_HOME=${BASE%"/"}/$USER_NAME

LOG_DIR=${LOG_DIR:-"$USER_HOME/.containers/logs"}
LOG_FILE="$LOG_DIR/${CONTAINER_NODE:-startup}.log"

mkdir -p "$LOG_DIR"
truncate --size=0 "$LOG_FILE"
start_runit > >(tee -a "$LOG_FILE") 2> >(tee -a "$LOG_FILE" >&2)
