name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:  
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - ROOT_IMAGE: ubuntu:18.04
            TAG: ubuntu18.04
          - ROOT_IMAGE: nvidia/cuda:10.1-cudnn7-devel-ubuntu18.04
            TAG: ubuntu18.04-cuda10.1
          
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Build and push base CCC image
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: vicoslab/ccc
        path: base
        tags: base-${{ matrix.TAG }}
        build_args: BUILDKIT_INLINE_CACHE=1,ROOT_IMAGE=${{ matrix.ROOT_IMAGE }}
        cache_froms: vicoslab/ccc:base-${{ matrix.TAG }}
        always_pull: true

    - name: Build and push jupyter CCC image
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: vicoslab/ccc
        path: jupyter
        tags: jupyter-${{ matrix.TAG }}
        build_args: BUILDKIT_INLINE_CACHE=1,ROOT_IMAGE=vicoslab/ccc:base-${{ matrix.TAG  }}
        cache_froms: vicoslab/ccc:jupyter-${{ matrix.TAG }},vicoslab/ccc:base-${{ matrix.TAG }}
        always_pull: true

    - name: Build and push X11 CCC image
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: vicoslab/ccc
        path: x11
        tags: x2go-${{ matrix.TAG }}
        build_args: BUILDKIT_INLINE_CACHE=1,ROOT_IMAGE=vicoslab/ccc:base-${{ matrix.TAG  }},X11_SERVER=x2go
        cache_froms: vicoslab/ccc:x2go-${{ matrix.TAG }},vicoslab/ccc:base-${{ matrix.TAG }}
        always_pull: true
